language: python
python:
- 2.7
- 3.5
- 3.6
matrix:
  allow_failures:
    - python: 3.6

env:
  - TEST_DIR=tests

sudo: false

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pillow cython ipython;
    else
      conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pillow cython ipython;
    fi
  - pip install -r requirements_dev.txt
  - pip install nose-cov python-coveralls pymatsolver
  - pip install nose-cov python-coveralls git+https://github.com/simpeg/simpeg.git@em/feat/3Dcyl
  - pip install nose-cov python-coveralls git+https://github.com/simpeg/discretize.git@feat/3Dcylmesh
  - python setup.py install
  - python setup.py build_ext --inplace

script:
  - nosetests $TEST_DIR

after_success:
  - bash <(curl -s https://codecov.io/bash)
